local config = require("lapis.config")
config("development", function()
  return port(8080)
end)
return config("production", function()
  port(80)
  num_workers(4)
  code_cache("on")
  return measure_performance(true)
end)
