local config = require("lapis.config")
config("development", function()
  port(8080)
  db_url("http://172.30.0.6:8529/")
  db_name("cms")
  db_login("root")
  return db_pass("password")
end)
return config("production", function()
  port(80)
  num_workers(4)
  code_cache("on")
  measure_performance(true)
  db_url("http://172.30.0.6:8529/")
  db_name("cms")
  db_login("root")
  return db_pass("password")
end)
